<?php

/**
 * @file
 * Drupal related MagPo operations.
 */

// Module constants.
define('FK_MAGPO_ENDPOINT', 'http://localhost:3000');
define('FK_MAGPO_STATUS_ENDPOINT', '/admin/%s/status');

/**
 * Implements hook_menu().
 */
function fk_magpo_menu() {
  $items = array();

  $items['admin/config/system/fk-magpo'] = array(
    'title' => 'Magnetic Poetry',
    'description' => 'Configure API endpoint for MagPo.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fk_magpo_settings'),
    'file' => 'fk_magpo.pages.inc',
    'access arguments' => array('administer site configuration'),
  );
  $items['magpo/json'] = array(
    'title' => 'Magnetic Poetry: JSON',
    'page callback' => 'fk_magpo_json',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_node_update().
 */
function fk_magpo_node_update($node) {
  if ($node->type !== 'poem' || empty($node->field_poem_unique_id['und'][0]['value'])) {
    return;
  }

  // Handle a published state change.
  if ($node->status !== $node->original->status) {
    fk_magpo_unpublish_poem($node);
  }
}

/**
 * Implements hook_node_delete().
 */
function fk_magpo_node_delete($node) {
  if ($node->type !== 'poem' || empty($node->field_poem_unique_id['und'][0]['value'])) {
    return;
  }

  // Set published status to false so the poem gets handled correctly.
  $node->status = 0;

  fk_magpo_unpublish_poem($node);
}

/**
 * Implements hook_form_FORM_ID_alter.
 *
 * @param $form
 *
 * @param $form_state
 *
 * @param $form_id
 *
 */
function fk_magpo_form_taxonomy_form_vocabulary_alter(&$form, &$form_state, $form_id) {
  // Prevent form from being created when it is confirm screen to delete.
  if (!isset($form['confirm'])) {
    $magpo = variable_get('fk_magpo_vocabularies', array());
    $vid = isset($form['vid']['#value']) ? $form['vid']['#value'] : 0;
    $form['#submit'][] = 'fk_magpo_form_taxonomy_form_vocabulary_submit';
    $form['fk_magpo'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use for Magnetic Poetry.'),
      '#default_value' => isset($magpo[$vid]),
    );
  }
}

/**
 * Custom submit function for
 *
 * @param $form
 *
 * @param $form_state
 *
 */
function fk_magpo_form_taxonomy_form_vocabulary_submit(&$form, &$form_state) {
  $magpo = variable_get('fk_magpo_vocabularies', array());
  // If the user deletes the vocabulary, remove it from the variable.
  // Else, add or remove it per the value of the checkbox.
  $value = $form_state['values']['op'] == 'Delete' ? FALSE : $form_state['values']['fk_magpo'];
  $vid = $form_state['values']['vid'];
  $name = $form_state['values']['name'];

  if ($value == FALSE && isset($magpo[$vid])) {
    unset($magpo[$vid]);
  }
  elseif ($value) {
    $magpo[$vid] = $name;
  }

  variable_set('fk_magpo_vocabularies', $magpo);
}

/**
 * Displays all vocabulary terms as a JSON export.
 */
function fk_magpo_json() {
  $vocabs = variable_get('fk_magpo_vocabularies', array());

  if (!is_array($vocabs)) {
    $vocabs = array();
    $temp = taxonomy_get_vocabularies();
    foreach($temp as $vid => $obj) {
      $vocabs[$vid] = $obj->name;
    }
  }

  $data = array();
  foreach($vocabs as $vid => $name) {
    $words = array();
    $query = db_select('taxonomy_term_data','t')
      ->fields('t', array('tid','name'))
      ->condition('vid', $vid, '=')
      ->orderBy('weight')
      ->execute();
    while ($row = $query->fetchObject()) {
      $words[] = array(
        'vid' => $vid,
        'id' => $row->tid,
        'string' => $row->name,
      );
    }

    $data[] = array(
      'id' => $vid,
      'name' => $name,
      'words' => $words,
    );
  }

  drupal_json_output($data);
}


function fk_magpo_preprocess_node(&$vars) {
  if (isset($vars['type']) && $vars['type'] == 'poem') {
    $uuid = $vars['field_poem_unique_id']['und'][0]['safe_value'];
    $url = "http://magpo.webchefs.org/magpo/app/load/" . $uuid;
    $return = drupal_http_request($url);
    drupal_add_js(array('fk_magpo' => array('json' => $return->data, 'uuid' => $uuid)), 'setting');
    drupal_add_js(drupal_get_path('module', 'fk_magpo') . '/fk_magpo.js');
    $vars['json_procesed_html'] = fk_magpo_json_process($return->data);
  }
}

function fk_magpo_json_process($json) {
  $object = json_decode($json);
  if(isset($object->status) && $object->status == 'ok') {
    $return = '<div class="fk-magpo-container-error">';
    foreach($object->poem->words as $word) {
      $return .= '<div class="fk-magpo-word fk-magpo-word-vid-' . $word->vid . '">' . $word->string . '</div>';
    }
    $return .= '</div>';
  }
  else {
    $return = '<div class="fk-magpo-container-error"></div>';
  };
  return $return;
}

/**
 * Unpublishes a poem on the node side when the poem node
 * has been unpublished or deleted.
 */
function fk_magpo_unpublish_poem($node) {
  $url = variable_get('fk_magpo_endpoint', FK_MAGPO_ENDPOINT) .
    sprintf(FK_MAGPO_STATUS_ENDPOINT, $node->field_poem_unique_id['und'][0]['value']);

  $options = array(
    'headers' => array(
      'Content-Type' => 'application/json'
    ),
    'method' => 'POST',
    'data' => drupal_json_encode(array('status' => (boolean)$node->status))
  );

  $res = drupal_http_request($url, $options);
  if ($res->code !== '204') {
    $data = new stdClass();
    if (!empty($res->data)) {
      $data = drupal_json_decode($res->data);
    }
    watchdog(
      'fk_magpo',
      'There was a problem updating status for node @nid with id @id. Server responded with: @message (@code)',
      array(
        '@nid' => $node->nid,
        '@id' => $node->field_poem_unique_id['und'][0]['value'],
        '@message' => isset($data->error) ? $data->error : (isset($res->error) ? $res->error : ''),
        '@code' => $res->code
      ),
      WATCHDOG_ERROR
    );
  }
}

